# Generated by Django 3.1.6 on 2021-07-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20, null=True)),
                ('price1', models.CharField(max_length=30, null=True)),
                ('price2', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(max_length=15, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
