# Generated by Django 3.1.6 on 2021-07-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(max_length=20, null=True)),
                ('feedback_contact', models.CharField(max_length=30, null=True)),
                ('feedback_email', models.CharField(max_length=10, null=True)),
                ('feedback_comment', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
