# Generated by Django 3.1.6 on 2021-07-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='booking_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
